import "./globals.css";
import { Metadata } from "next";

// import google fonts
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* apply font to entire app */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
