import Link from "next/link";
import styles from "./page.module.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className={styles.navbar}>
          <Link href="/">Home</Link>
          <Link href="about">About</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
